name: DECCON
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py310h6a678d5_7
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cryptography=41.0.7=py310hdda0065_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h5eee18b_0
  - ffmpeg=4.3=hf484d3e_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - imagecodecs=2023.1.23=py310hc4b7b5f_0
  - imageio=2.33.1=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.2.0=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.3=py310h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libavif=0.11.1=h5eee18b_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcurl=8.7.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libzopfli=1.0.3=he6710b0_0
  - lmdb=0.9.29=h2531618_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-base=3.8.0=py310h1128e8f_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.3=py310h5f9d8c6_0
  - numpy-base=1.26.3=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_1
  - pandas=2.2.1=py310h6a678d5_0
  - pillow=10.0.1=py310ha6cbd5a_0
  - pip=23.3.1=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=1.12.0=py3.10_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - scikit-image=0.22.0=py310h1128e8f_0
  - scikit-learn=1.3.0=py310h1128e8f_1
  - scipy=1.11.4=py310h5f9d8c6_0
  - seaborn=0.12.2=py310h06a4308_0
  - setuptools=68.2.2=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2023.4.12=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.13.0=py310_cu113
  - tqdm=4.65.0=py310h2f386ee_0
  - typing_extensions=4.9.0=py310h06a4308_1
  - tzdata=2023d=h04d1e81_0
  - urllib3=1.26.18=py310h06a4308_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zfp=1.0.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - comm==0.2.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - faiss-cpu==1.8.0
      - fastjsonschema==2.19.1
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - ipykernel==6.29.3
      - ipython==8.22.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - json5==0.9.19
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.3
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - nbclient==0.9.0
      - nbconvert==7.16.1
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.1.1
      - notebook-shim==0.2.4
      - opencv-python==4.9.0.80
      - overrides==7.7.0
      - packaging==23.2
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pexpect==4.9.0
      - platformdirs==4.2.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.17.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - referencing==0.33.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - send2trash==1.8.2
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - terminado==0.18.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.4
      - traitlets==5.14.1
      - types-python-dateutil==2.8.19.20240106
      - uri-template==1.3.0
      - wand==0.6.13
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
prefix: /home/pal194/miniconda3/envs/py_plot
